infrastructure:
  env: dev
spring:
  kafka:
    bootstrap-servers:
      - host.docker.internal:29092
#      - localhost:9092
#      - localhost:9093
#      - localhost:9094
#      - localhost:9095
#      - localhost:9096
#      - localhost:9097
    consumer:
      enable-auto-commit: false
      isolation-level: read_committed
      group-id: ${infrastructure.env}-appointment-notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      max-poll-records: 10
      properties:
        max.poll.interval.ms: 600000
    listener:
      ack-mode: manual_immediate
      concurrency: 1
      auto-startup: true
    properties:
      security.protocol: PLAINTEXT
      sasl.mechanism: PLAIN
  mail:
    host: smtp.gmail.com
    port: 587
    username: "menelis.m@gmail.com"
    password: "oyij czjn tnjt pfvl"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true
app:
  kafka:
    consumer:
      topic:
        name: ${infrastructure.env}-appointment-notifications
        topic-header-filter:
          header-key: eventType
          header-values:
            - verifyEmail
            - bookingConfirmed
            - bookingPendingConfirmed
            - bookingCancelled
            - passwordReset

  encryption-key: "AHaeXmeTddI9EsmAOiK2l8diUFH5htXacTEP4wa5zBs="
  mail:
    from-address: ${spring.mail.username}
