spring:
  application:
    name: appointment-gateway
  cloud:
    config:
      enabled: false
    gateway:
      server:
        webflux:
          default-filters:
            - TokenRelay=
          routes:
            - id: branch-service
              uri: http://localhost:9002
              predicates:
                - Path=/api/v1/branch/**,/api/v1/province/**,/api/v1/city/**
            - id: appointment-service
              uri: http://localhost:9003
              predicates:
                - Path=/api/v1/appointment/**,/api/v1/slot/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks
          issuer-uri: http://127.0.0.1:9000
app:
  open-api:
    info:
      title: Appointment API Gateway Service
      description: Appointment API Gateway Service
      version: 1.0.0
  cors:
    allowed-origins:
      - http://localhost:4200 # UI
    allowed-methods:
      - "*"
    allowed-headers:
      - "*"
    max-age: 3600
  white-list:
    - "/v3/api-docs/**"
    - "/swagger-ui/**"
    - "/auth-service/swagger-ui/**"
    - "/auth-service/v3/api-docs/**"
    - "/api/v1/account/**"
    - "/branch-service/swagger-ui/**"
    - "/branch-service/v3/api-docs/**"
    - "/appointment-service/swagger-ui/**"
    - "/appointment-service/v3/api-docs/**"
  admin-routes:
    - "/api/v1/branch/admin/**"
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    doc-expansion: none
    urls:
      - name: gateway-service
        url: ${springdoc.api-docs.path}
      - name: auth-service
        url: http://localhost:9000/auth-service/v3/api-docs
      - name: branch-service
        url: http://localhost:9002/branch-service/v3/api-docs
      - name: appointment-service
        url: http://localhost:9003/appointment-service/v3/api-docs
logging:
  level:
    root: trace

