infrastructure:
  ENV: dev
  DB:
    USERNAME: appointment_service_user
    PASSWORD: appointment_service_user

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_auth_service_dev
    username: ${infrastructure.DB.USERNAME}
    password: ${infrastructure.DB.PASSWORD}
  flyway:
    schemas: public
    baseline-version: 2.0.0 # The increment is based on existing tables
    baseline-description: Base Migration
    enabled: false
    baseline-on-migrate: true
    ignore-migration-patterns:
      - "*:missing"
    clean-disabled: false
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
  kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093
      - localhost:9094
      - localhost:9095
      - localhost:9096
      - localhost:9097
    producer:
      acks: -1
      batch-size: 100
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: zstd
springdoc:
  api-docs:
    path: /auth-service/v3/api-docs
  swagger-ui:
    path: /auth-service/swagger-ui.html
    operations-sorter: method
    doc-expansion: none

app:
  email-template:
    verify-email-template: Hi %s,<br/><br/> Welcome to Appointment System.To complete registration process click <a href='%s'>here</a> to verify your account.<br/></br/><br/><br/> %s
    reset-password-email-template: Hi %s,<br/><br/> We have received your request to reset your password.Please click <a href='%s'>here</a> to reset your password.<br/></br/><br/> %s
  cors:
    allowed-origins:
      - http://localhost:4200
    allowed-methods:
      - POST
      - GET
      - PUT
      - OPTIONS
      - DELETE
      - PATCH
    allowed-headers:
      - "*"
    max-age: 3600
  white-list:
    - "/auth-service/v3/api-docs/**"
    - "/auth-service/swagger-ui/**"
    - "/api/v1/auth/**"
  custom-exposed-endpoints:
    - "/api/v1/auth/**"
  open-api:
    info:
      title: Appointment Auth Service
      description: Appointment Authentication Service
      version: 1.0.0
  verification-token:
    expiration-ms: 86400000
  kafka:
    notification-topic: ${infrastructure.ENV}-appointment-notifications
  encryption-key: "AHaeXmeTddI9EsmAOiK2l8diUFH5htXacTEP4wa5zBs="
  registered-clients:
    -
      # Public Client for UI
      client-id: appointment-ui-client
      client-authentication-methods:
        - "none"
      authorization-grant-types:
        - "authorization_code"
        - "refresh_token"
      redirect-uris:
        - "${app.client-url}/callback"
      post-logout-redirect-uris:
        - "${app.client-url}/account/sign-out"
      scopes:
        - "openid"
        - "profile"
        - "email"
      client-settings:
        require-proof-of-key: true
      token-setting:
        access-token-time-to-live: 120 # in minutes
        refresh-token-time-to-live: 1 # in days
  client-url: http://localhost:4200


server:
#  address: 127.0.0.1
#  port: 9000
  error:
    whitelabel:
      enabled: true
#grpc:
#  server:
#    port: 9090
#
#
#logging:
#  level:
#    root: trace
#    #org.springframework.security.oauth2.server.authorization.oidc.web: trace
#    #org.springframework.security.web: trace