infrastructure:
  environment: PROD
spring:
  application:
    name: personal-savings-api
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: none #redis
    redis:
      time-to-live: 60m
      enable-statistics: true
      cache-null-values: false
      use-key-prefix: false
  datasource:
    url: jdbc:sqlserver://localhost;encrypt=true;trustServerCertificate=true;databaseName=personal_savings_prd
    username: personal_savings_api_prd
    password: personal_savings_api_prd
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        connection:
          url: ${spring.datasource.url}
          pool_size: 10
        format_sql: false
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: "menelis.m@gmail.com"
    password: "oyij czjn tnjt pfvl"
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    doc-expansion: none


app:
  jwt:
    secret: "U0ZDuF5Gn6WF5aapuNXgkKQcjKFA5eHEbOMKxQnOayI="
    expiration-ms: 7200000 # 2 hours
  cors:
    allowed-methods:
      - "*"
    allowed-headers:
      - "*"
    allowed-origins:
      - http://localhost:657
  open-api:
    title: Personal Savings Api ${infrastructure.environment}
    description: Personal Savings Api for front end
    version: 1.0
    contact-info:
      name: Menelisi Mthembu
      email: menelis@email.com
      url: https://www.menelis.co.za
    license-info:
      name: License for API
      url: https://www.mta.com
  white-list:
    - "/api-docs/**"
    - "/swagger-ui/**"
    - "/error"
    - "/api/auth/*"
  mail:
    from: ${spring.mail.username}
    subject: Email Verification
    expiration-in-ms: 86400000 # 24 hours
  client:
    url: http://localhost:657
    email-confirm-url: ${app.client-url}/account/confirmPassword
    forgot-password-url: ${app.client.url}/account/forgotPassword
  admin-routes:
    - "/api/transaction-type/admin/**"
    - "/api/account-type/admin/**"
    - "/api/running-year/admin/**"
    - "/api/account/admin/**"
  # Seed the app with admin users.If not supplied(first-name,last-name) they will be defaulted to admin
  admins:
    -
      email: "admin@personalsavings.co.za"
    -
      email: "admin2@personalsavings.co.za"
